### ISSUE TITLE
Health Tracker & Willpower Tracker

### ISSUE THREAD

**Issue by wmarrison** [MrDionysus/foundry-WOD5#3]
Health Tracker and Willpower Tracker bug out when added to. Either the boxes cannot be checked, or they disappear shortly after being checked.

**Comment by wmarrison** [comment]
This is specifically and only on the Hunter Sheets, as far as I can see.

**Comment by MrDionysus** [comment]
Thank you for the feedback!  Apparently I broke that while trying to get the despair button to work properly.  I've updated the code and it seems to be fixed now.
